### ISSUE TITLE
Believe Problem has to do with Address

### ISSUE THREAD

**Issue by maxmehlbaum** [OpenSTFoundation/openst-platform#91]
Ok so im going to go through everything ive done , so far so its easier to find the problem im having.
so I downloaded geth through home-brew and im running geth on a terminal. from what I understand geth allows you to keep a record of each ethereum block. so when it reached around the 3 million block range I started the process in the read.me...

so I run the steps in the read.me:

I went to the proper repo of OpenST Platform

I installed the packages 

"npm install"

and I received 

up to date in 11.285s

so that seems to be an update.

I then deleted the old chains and it seems as though nothing happened. 

next I go into test through - cd test 

I run the command 

> ./init_keys.sh

I receive this warning:
WARN [01-17|11:09:25] No etherbase set and no accounts found as default

I also see this within the output:

--------------------------------------------------
...Done Init
Generate new addresses...
...New addresses generated
Sync keystores
...keystores synced

--------------------------------------------------

I then open terminal 2 
and run the commands and am in the test directory.

I run the command:

./run_value_chain.sh

I receive this warning at the top of the output in terminal:

_________________________________________________

WARN [01-17|11:14:13] Upgrading database to use lookup entries

& this warning at the bottom:

Fatal: Error starting protocol stack: listen udp :30303: bind: address already in use

__________________________________________________

so im assuming because is the 3rd of fourth time ive tried this that I already have a unique address ready to use in order to create coins with. 

then I run the commands in the test directory for terminal 3:

./run_utility_chain.sh

I receive this warning at the top of the output 

WARN [01-17|11:18:14] Upgrading database to use lookup entries

from what I see, it looks as though the utility chain is the record of all blocks for the new coin im creating. hence 

________________________________________________________

INFO [01-17|11:18:17] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=208.577µs
INFO [01-17|11:18:19] Successfully sealed new block            number=1 hash=ec4994…0bd411
INFO [01-17|11:18:19] 🔨 mined potential block                  number=1 hash=ec4994…0bd411

________________________________________________________

I then go back to terminal 1 and enter cd .. and am In the openst-platform-master directory

I run 

>source test/open_st_env_vars.sh

and nothing happens really except the fact that im able to run a new command 

so I run

> ./run_complete_test_deploy.sh

and I receive this error within the output

ERROR :: Invalid Registrar address 

I then type Y, Y , Y when prompted with the questions and then receive 

sendTransaction :: callback :: error null

----> addressToNameMap undefined
------> addressToNameMap undefined

Failed to fund  Address 

(node:20713) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid JSON RPC response: ""
(node:20713) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

So thats where I am currently at. Im assuming the address has to be staked and backed by Simple tokens in order to create more tokens, if so how do u connect the simple token wallet onto the new coin im creating. or could it be that I made a mistake somewhere In the beginning and it is causing me to keep receiving these error messages. would love to know what you see

thanks, 
max

**Comment by jasonklein** [comment]
@maxmehlbaum: the comments/questions above suggest that certain matters should be clarified. Please read the below (apologies if it's overly pedantic!), review the steps you've taken thus far in light of any revised understanding, and let us know whether (1) there remain concerns to be resolved and (2) whether retrying succeeds.

**Components:**

- `test/open_st_env_vars.sh`
  - makes environment variables available in the shell—initially (as viewable here on GH) many are empty strings
  - `source` (re)executes the commands, because the file will be written to by certain of the scripts that will be executed in this process—successfully `source`-ing this file will not produce any terminal output
- `test/init_keys.sh`
  - initializes two blockchains, one to be used as the value chain and one to be used as the utility chain (see [OpenST Protocol White Paper](https://drive.google.com/file/d/0Bwgf8QuAEOb7Z2xIeUlLd21DSjQ/view))
  - generates keys that will act in certain roles on the chains
  - overwrites (essentially) the definitions of the corresponding environment variables with the  freshly generated keys in `test/open_st_env_vars.sh`
- `test/run_value_chain.sh` re-starts the value chain, which was initialized by `test/init_keys.sh`
- `test/run_utility_chain.sh` re-starts the utility chain, which was initialized by `test/init_keys.sh`
- `./run_complete_test_deploy.sh`
  - via multiple node scripts, acts through the roles/accounts generated by `test/init_keys.sh`
  - deploys protocol contracts to the chains as needed
  - takes actions necessary to prepare the two chains for test staking and minting, including:
    - transferring utility chain base tokens ("ST Prime") to enable executing transactions on the utility chain
    - deploying a `BrandedToken` with the name "Acme Coin" and symbol "ACME"

**Steps** (assuming a fresh install, after running `npm install`, and after removing any old chain data (if starting fresh, this should get a no file found response, otherwise it executes but does not produce any terminal output)):

- after executing `init_keys.sh`
  - two chains will be initialized, accounts will have been generated, and vars initially defined as empty in `open_st_env_vars.sh` will have addresses for definitions
  - if either `run_value_chain.sh` or `run_utility_chain.sh` is executed`init_keys.sh` has been run and completed, errors will be encountered then and later
- after executing `run_value_chain.sh` and `run_utility_chain.sh` in different terminals, you will see lots of output
  - these are the blockchains running
  - at this point, the chains will be  mining/sealing empty blocks (see `txs=0` from the output provided above)
> it looks as though the utility chain is the record of all blocks for the new coin im creating
  - the foregoing statement is somewhat inapposite because
    - there are not yet any transactions
    - the blocks are for all transactions submitted, not just the ones concerning a particular token
    - as there are no transactions yet, there is no token being created
    - (and, not to put too fine a point on it, but) in this flow, our scripts will create a coin, Acme Coin, on your behalf
- after executing `run_complete_test_deploy.sh`, if all of the preceding steps have been successfully followed and if "Y" is given at every prompt:
  - there will be a **great deal** of output:
    - narration of what is taking place (e.g., "Transferred all ST Prime Base Tokens to STPrime Contract Address", "Address has been transfered 1000000000000000000 on UtilityChain")
    - transaction logs from the chains (hashes, bytecode, etc.)
  - the blockchains running in the other terminals will correspond to the output from the script (e.g., the script may say "Waiting for 0x... to be mined" and that hash should appear in the relevant blockchain terminal

**Comment by jasonklein** [comment]
@maxmehlbaum: was the information above helpful and have you been able to move forward?

**Comment by maxmehlbaum** [comment]
Yeah so right now we’ve executed the node services/inter_comm/stake_and_mint.js and it just has stayed at

Intercomm script for stake and mint initiated
________________________________

**Comment by jasonklein** [comment]
Closing this as #93 was opened with additional troubleshooting details.
