### ISSUE TITLE
Intercomm script for stake and mint Time Frame Slow

### ISSUE THREAD

**Issue by maxmehlbaum** [OpenSTFoundation/openst-platform#92]
Stake Simple Tokens on value chain to mint Branded Tokens
In Terminal 1:
Start the stake and mint intercom process while branded tokens are minted (NOTE: This process need to be running till Terminal 2 process ends)
  > cd openst-platform
  > source test/open_st_env_vars.sh
  > node services/inter_comm/stake_and_mint.js

we ran these steps and they were all successful potential until node services/inter_comm/stake_and_mint.js where it has just left us in terminal one with:

"InterComm Script for Stake and Mint initiated"

 terminal 2 is still running. so im assuming that it has to do with the fact that they are still being minted in this terminal and i have a macbook air so the processing power is slow?

**Comment by jasonklein** [comment]
Closing this as #93 was opened with additional troubleshooting details.

For posterity, will note: after starting (and leaving to run) the chains in two terminals windows and running the `node services/inter_comm/stake_and_mint.js` script in different terminal window, `node tools/stake_and_mint/for_branded_token.js` should be run in a fourth/different terminal window in order to stake and mint, as described in the test [README](https://github.com/OpenSTFoundation/openst-platform/tree/master/test#in-terminal-4).
